### ISSUE TITLE
Script fails on some chapters

### ISSUE THREAD

**Issue by samarthbhargav** [AnimeshShaw/MangaScrapper#1]
To reproduce:
`python mangascrapper.py  -c 89 "Naruto"`

Error:

```
Traceback (most recent call last):
  File "mangascrapper.py", line 287, in <module>
    main()
  File "mangascrapper.py", line 283, in main
    scrape.start_scrapping()
  File "mangascrapper.py", line 161, in start_scrapping
    doc.build(parts)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 1117, in build
    BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 880, in build
    self.handle_flowable(flowables)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 793, in handle_flowable
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: Flowable <Image at 0x21f0560 frame=normal filename=/home/hduser/env/MangaScrapper-master/mangascrapper/Naruto/Chapter 89 - Naruto&#039;s Request!! /1.jpg> too large on page 2 in frame 'normal'(1034.5511811 x 1527.77952756*) of template 'Later'
```

**Comment by AnimeshShaw** [comment]
Thats because sometimes the images are too big to fit in a page. The default page size is A2. All I have to do is re-size all the images before saving and that should do the trick. With todays release it should be done :+1:
